### ISSUE TITLE
Validators - nested properties only generates numbers

### ISSUE THREAD

**Issue by Ovoda** [ad-on-is/adonis-autoswagger#119]
Hello,

It looks like the types generated from a deeply nested validator are wrong.

Let me know if you need more information. I'm down to help, not sure how tho.

Example:

```ts
export const labelCreateValidator = vine.compile(
  vine.object({
    // level 1
    string1: vine.string(),
    object1: vine.object({
      // level 2
      string2: vine.string(),
      object2: vine.object({
        // level 3
        string3: vine.string(),
        object3: vine.object({
          // level 4
          string4: vine.string(),
        }),
      }),
    }),
  })
)
```

```yaml
labelCreateValidator:
  type: "object"
  properties:
    string1:
      type: "string"
      example: "Lorem Ipsum"
      required: true
    object1:
      type: "object"
      properties:
        string2:
          type: "string"
          example: "Lorem Ipsum"
          required: true
        object2:
          type: "object"
          properties:
            string3:
              type: "number" # <- wrong type here
              example: 964
              required: true
            object3:
              type: "object"
              properties:
                string4:
                  type: "number" # <- wrong type here
                  example: 109
                  required: true
              required: true
          required: true
         # Not sure why they appear here again, with the right types
          string3:
            type: "string"
            example: "Lorem Ipsum"
          object3:
            string4:
              type: "string"
              example: "Lorem Ipsum"
```
