### ISSUE TITLE
Describing data types for models

### ISSUE THREAD

**Issue by IgoP02** [ad-on-is/adonis-autoswagger#51]
Is it possible to describe data types in schemas using keywords? After reading the guide I haven't been able to think of a way to do it. 

I've also tried directly modifying the generated swagger.yml file and adding some keywords:

```
    Brand:
      type: "object"
      properties:
        id:
          type: "number"
          example: 164
        name:
          type: "string"
          example: "John Doe"
          minLength: 1
          maxLength: 100
        created_by:
          type: "number"
          example: 638
```
But even then they won't show up the in schema section on the docs:

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/40871105/86f6f214-a4fe-4a35-a478-d5d4257a45da)
